name: tfgrid-wordpress
version: "1.0.0"
description: Self-hosted WordPress with Caddy and MariaDB

patterns:
  recommended: single-vm
  supported:
    - single-vm

resources:
  cpu:
    min: 1
    recommended: 2
  memory:
    min: 1024
    recommended: 2048
  disk:
    min: 20
    recommended: 50
  ports:
    - 22:ssh
    - 80:http
    - 443:https

hooks:
  setup: deployment/setup.sh
  configure: deployment/configure.sh
  healthcheck: deployment/healthcheck.sh

environment:
  # Domain Configuration
  - name: DOMAIN
    required: true
    description: "Public domain for WordPress (e.g., blog.example.com)"
  - name: SSL_EMAIL
    required: false
    description: "Email for Let's Encrypt SSL certificates"
    
  # DNS Automation (name.com, cloudflare, godaddy recommended for full automation)
  - name: DNS_PROVIDER
    required: false
    description: "DNS provider for automatic A record setup"
    options:
      - manual
      - name.com
      - cloudflare
      - godaddy
      - namecheap  # Requires manual IP whitelisting in Namecheap dashboard
    default: "manual"
  - name: NAMECOM_USERNAME
    required: false
    description: "Name.com username"
    depends_on:
      DNS_PROVIDER: "name.com"
  - name: NAMECOM_API_TOKEN
    required: false
    secret: true
    description: "Name.com API token"
    depends_on:
      DNS_PROVIDER: "name.com"
  - name: CLOUDFLARE_API_TOKEN
    required: false
    secret: true
    description: "Cloudflare API token"
    depends_on:
      DNS_PROVIDER: "cloudflare"
  - name: GODADDY_API_KEY
    required: false
    description: "GoDaddy API key"
    depends_on:
      DNS_PROVIDER: "godaddy"
  - name: GODADDY_API_SECRET
    required: false
    secret: true
    description: "GoDaddy API secret"
    depends_on:
      DNS_PROVIDER: "godaddy"
  - name: NAMECHEAP_API_USER
    required: false
    description: "Namecheap API username (requires IP whitelisting - not fully automated)"
    depends_on:
      DNS_PROVIDER: "namecheap"
  - name: NAMECHEAP_API_KEY
    required: false
    secret: true
    description: "Namecheap API key (requires IP whitelisting - not fully automated)"
    depends_on:
      DNS_PROVIDER: "namecheap"
      
  # WordPress Configuration
  - name: WP_ADMIN_USER
    required: false
    description: "WordPress admin username"
    default: "admin"
  - name: WP_ADMIN_EMAIL
    required: false
    description: "WordPress admin email"
  - name: WP_SITE_TITLE
    required: false
    description: "WordPress site title"
    default: "My WordPress Site"
  - name: WP_LOCALE
    required: false
    description: "WordPress language/locale"
    default: "en_US"
    
  # Performance Settings
  - name: PHP_MEMORY_LIMIT
    required: false
    description: "PHP memory limit"
    default: "256M"
  - name: PHP_UPLOAD_MAX
    required: false
    description: "Maximum upload file size"
    default: "64M"
  - name: WP_DEBUG
    required: false
    description: "Enable WordPress debug mode"
    default: "false"
    
  # Database Configuration
  - name: DB_PASSWORD
    required: false
    secret: true
    description: "MariaDB password (auto-generated if not set)"
  - name: DB_ROOT_PASSWORD
    required: false
    secret: true
    description: "MariaDB root password (auto-generated if not set)"
    
  # Backup Configuration
  - name: BACKUP_RETENTION_DAYS
    required: false
    description: "Number of days to keep backups"
    default: "30"

commands:
  backup:
    script: /opt/wordpress/scripts/backup.sh
    description: "Create full backup (files + database)"
    args: "[--output /path/to/backup.tar.gz]"
  restore:
    script: /opt/wordpress/scripts/restore.sh
    description: "Restore from backup"
    args: "--backup /path/to/backup.tar.gz"
  list-backups:
    script: /opt/wordpress/scripts/list-backups.sh
    description: "List available backups"
  logs:
    script: /opt/wordpress/scripts/logs.sh
    description: "View WordPress and MariaDB logs"
    args: "[wordpress|db|caddy] [--follow]"
  shell:
    script: /opt/wordpress/scripts/shell.sh
    description: "Open WordPress container shell"
  wp:
    script: /opt/wordpress/scripts/wp-cli.sh
    description: "Run WP-CLI commands"
    args: "<wp-cli-command>"
  restart:
    script: /opt/wordpress/scripts/restart.sh
    description: "Restart WordPress services"

status:
  check_interval: 60
  endpoints:
    - path: /
      expected_status: 200

logging:
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

tags:
  - wordpress
  - cms
  - blog
  - docker
  - caddy
  - mariadb
